### ISSUE TITLE
GNU Radio 3.7

### ISSUE THREAD

**Issue by WGH-** [bitglue/gr-pulseaudio#1]
Apparently, support for 3.7 exists in `travistaketwo` branch, but it has never been merged in master. Why?

**Comment by bitglue** [comment]
Honestly, I totally forgot I even did this :)

**Comment by WGH-** [comment]
The code seems to be more or less working, BTW. I made a few adjustments, though, and will submit them as pull requests.

**Comment by bitglue** [comment]
Awesome, thank you!

**Comment by WGH-** [comment]
It seems it's already in master.
